apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dfactory.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dfactory.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dfactory.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "dfactory.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: dfactory
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: DFACTORY_API_KEY
              value: {{ .Values.env.DFACTORY_API_KEY | quote }}
          readinessProbe:
            httpGet:
              path: /api/ready
              port: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
